---
apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata: 
  name: "spark"
  namespace: "mlops"
  labels: 
    description: ""
spec: 
  app: "spark245-custom"
  namingScheme: "CrNameRole"
  appCatalog: "local"
  connections: {}
  roles: 
    - 
      id: "spark-master"
      members: 1
      resources: 
        requests: 
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "0"
        limits: 
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "0"
      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      podLabels: 
        hpecp.hpe.com/dtap: "hadoop2"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - stable207.container.demo.local  
    - 
      id: "livy-server"
      members: 1
      resources: 
        requests: 
          cpu: "2"
          memory: "6Gi"
          nvidia.com/gpu: "0"
        limits: 
          cpu: "2"
          memory: "6Gi"
          nvidia.com/gpu: "0"
      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      podLabels: 
        hpecp.hpe.com/dtap: "hadoop2"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - stable207.container.demo.local  
    - 
      id: "spark-worker"
      members: 2
      resources: 
        requests: 
          cpu: "4"
          memory: "5Gi"
          nvidia.com/gpu: "0"
        limits: 
          cpu: "4"
          memory: "5Gi"
          nvidia.com/gpu: "0"
      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      podLabels: 
        hpecp.hpe.com/dtap: "hadoop2"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - stable210.container.demo.local  
    - 
      id: "notebook-server"
      members: 1
      resources: 
        requests: 
          cpu: "1"
          memory: "2Gi"
          nvidia.com/gpu: "0"
        limits: 
          cpu: "1"
          memory: "2Gi"
          nvidia.com/gpu: "0"
      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      podLabels: 
        hpecp.hpe.com/dtap: "hadoop2"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - stable207.container.demo.local  