apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hiveMetastore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    app.kubernetes.io/component: metastore
    {{- include "hiveMetastore.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hiveMetastore.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        hpecp.hpe.com/dtap: hadoop2
        app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: metastore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: HADOOP_CLASSPATH
          value: "/opt/bdfs/bluedata-dtap.jar"
        - name: CLASSPATH
          value: "/opt/bdfs/bluedata-dtap.jar"
        - name: HIVE_AUX_JARS_PATH
          value: "/opt/bdfs/bluedata-dtap.jar"
        command:
        - sh
        - -exc
        - |
          sleep 180 &&\
          sed -i 's+<configuration>+<configuration>\n  <property>\n    <name>fs.dtap.impl</name>\n    <value>com.bluedata.hadoop.bdfs.Bdfs</value>\n  </property>\n  <property>\n      <name>fs.AbstractFileSystem.dtap.impl</name>\n      <value>com.bluedata.hadoop.bdfs.BdAbstractFS</value>\n  </property>+' /opt/hadoop-2.7.4/etc/hadoop/core-site.xml  &&\
          exec /opt/hive/bin/hive --service metastore
        resources:
          # &&
          # exec /opt/hive/bin/schematool -initSchema -dbType postgres &&
{{ toYaml .Values.resources | indent 10 }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 16010
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 16010
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 2
        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive/conf
      volumes:
      - name: hive-config
        configMap:
          name: {{ include "hiveMetastore.fullname" . }}
